### ISSUE TITLE
Java CI Related issues

### ISSUE THREAD

**Issue by blaketingyu** [nus-cs2103-AY2122S2/forum#123]
Greetings everyone, 
I'm not sure how to fix this issue. I'm failing my java CI test because in the IO redirection as seen below.
![image](https://user-images.githubusercontent.com/77196632/152838097-0bba6c32-d03c-40bf-b894-457cabfd6d80.png)
![image](https://user-images.githubusercontent.com/77196632/152838154-428e09b5-bd34-4c65-b00c-60b32bee5f2e.png)

The log to the issue can be accessed here: 
https://github.com/blaketingyu/ip/runs/5097132482?check_suite_focus=true

Thank you !

**Comment by domlimm** [comment]
Hello @blaketingyu ! Try removing these lines from your `gradle.yml` file:

```yml
      - name: Perform IO redirection test (*NIX)
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (MacOS)
        if: always() && runner.os == 'macOS'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (Windows)
        if: always() && runner.os == 'Windows'
        working-directory:  ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat
```
