### ISSUE TITLE
AB-3 Header when printing tP website pages

### ISSUE THREAD

**Issue by snss231** [nus-cs2103-AY2122S2/forum#241]
Hey guys! Think most of us encountered the issue where there's this annoying AB-3 header when trying to print our UG/DG as pdf. Tried scouring through the files in the /docs directory to no avail. I know we can just edit the pdf using an editor, but does anyone have a solution to this?

![2022-03-29 20 27 32](https://user-images.githubusercontent.com/77093722/160611103-febc135b-6923-41e1-b2a1-e37330606d78.jpg)

**Comment by yusufaine** [comment]
This was something that was annoying me as well and I had a feeling it was in one of the CSS files since this only affected how the guides were printed and saw this section in `_base.scss`. 

To find the file, you can press `Shift` twice and look for "_base.scss" or access `docs/_sass/minima/_base.scss` and just edit line #292 to the name of your project (as seen below).

```css
@media print {
  /**
  * Prevents page break from cutting through content when printing
  */
  body {
    display: block;
  }
  /**
  * Replaces the top navigation menu with the project name when printing
  */
  .site-header .wrapper {
    display: none;
  }
  .site-header {
    text-align: center;
    font-size: 32px;
  }
  .site-header:before {
    content: "<name of your project here>";
    font-size: 32px;
  }
}

```

Hope this helps 😄
