### ISSUE TITLE
Conversion to PDF -- Update header from AB-3 to the name of your project

### ISSUE THREAD

**Issue by yusufaine** [nus-cs2103-AY2122S2/forum#259]
By default, the PDF conversion works well but there was this detail that was annoying me -- the header of the file is titled AB-3. 

![telegram-cloud-photo-size-5-6197340175940562847-y](https://user-images.githubusercontent.com/29030941/162013914-4351ef4a-9557-4257-8994-464b19f29d01.jpg)

This was something that was bugging me and finally found what needed to be changed to update it.

1. Locate `_base.scss`, (tip: hit `Shift` twice and search for that file)
2. Look for `.site-header:before` and edit the content similar to what you see below

```scss
@media print {
  /**
  * Prevents page break from cutting through content when printing
  */
  body {
    display: block;
  }
  /**
  * Replaces the top navigation menu with the project name when printing
  */
  .site-header .wrapper {
    display: none;
  }
  .site-header {
    text-align: center;
    font-size: 32px;
  }
  .site-header:before {
    content: "<name of your project here>";
    font-size: 32px;
  }
}
```
